### ISSUE TITLE
bug: if local machine has a kind installation already, porter fails

### ISSUE THREAD

**Issue by kurktchiev** [back-stack/showcase#37]
If you have a kind cluster up locally, `porter install --param cluster-type=kind` fails to proceed. I did not have a chance to debug thoroughly, but the fix locally was to delete my existing kind cluster, which allowed the installation to proceed. We need to figure out where/why the clash was happening.

**Comment by morey-tech** [comment]
Strange, the Porter install should [be aware that the kind cluster already exists](https://github.com/back-stack/showcase/blob/5c20ec20f3a9e50d0a2bafa5733c49f499f3411b/bundle/helpers.sh#L114) and avoid conflicts. Can you post the error you run into?

**Comment by kurktchiev** [comment]
No it wasn’t that a backstack cluster already existed, it was having issues with the fact that there were other kind instances running locally.

I will rerun and try to grab the issue again next week

-B

**Comment by kurktchiev** [comment]
i cannot reproduce this anymore locally, but in that time `kind` got updated so maybe it was red herring.

**Comment by kurktchiev** [comment]
Found the problem. in our kind.config we bind 80/443 which in turn means we cannot stand up more instances
```
apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"        
  extraPortMappings:
  - containerPort: 80
    hostPort: 80
    protocol: TCP
  - containerPort: 443
    hostPort: 443
    protocol: TCP
```
So if I want to stand up another instance of the HUB on my local host, it will fail. This is isolated to KinD
